// Theme codes: G=Gift from God, L=Light, N=Nature, F=Faith, S=Strength, V=Love, W=Wisdom, R=Freedom, E=Grace, H=Hope
// Uniqueness: 1=Common 2=Uncommon 3=Rare 4=Very Rare
export const GIRLS=[
{n:"Aisha",o:"Arabic",m:"Alive, living well",s:3,t:["F","V"],u:1},
{n:"Amira",o:"Arabic",m:"Princess, commander",s:3,t:["S","E"],u:1},
{n:"Amina",o:"Arabic",m:"Trustworthy, faithful",s:3,t:["F","G"],u:1},
{n:"Arwa",o:"Arabic",m:"Mountain gazelle, blessing",s:2,t:["N","G"],u:2},
{n:"Asma",o:"Arabic",m:"Supreme, exalted",s:2,t:["S","W"],u:2},
{n:"Basma",o:"Arabic",m:"Smile, joy",s:2,t:["V","H"],u:2},
{n:"Dalal",o:"Arabic",m:"Coquettish, pampered",s:2,t:["E","V"],u:2},
{n:"Dalya",o:"Arabic",m:"Gentle branch, vine",s:3,t:["N","G"],u:2},
{n:"Duha",o:"Arabic",m:"Forenoon light",s:2,t:["L","H"],u:2},
{n:"Farah",o:"Arabic",m:"Joy, happiness",s:2,t:["V","H"],u:2},
{n:"Fatima",o:"Arabic",m:"Captivating, devoted",s:3,t:["F","G"],u:1},
{n:"Ghada",o:"Arabic",m:"Graceful young woman",s:2,t:["E","N"],u:2},
{n:"Hana",o:"Arabic",m:"Bliss, happiness",s:2,t:["V","H"],u:2},
{n:"Hayat",o:"Arabic",m:"Life itself",s:2,t:["H","N"],u:2},
{n:"Hessa",o:"Arabic",m:"Destiny, fate",s:2,t:["F","W"],u:3},
{n:"Hiba",o:"Arabic",m:"Gift from God",s:2,t:["G","F"],u:2},
{n:"Huda",o:"Arabic",m:"Right guidance from God",s:2,t:["F","W"],u:2},
{n:"Jana",o:"Arabic",m:"Paradise, heaven",s:2,t:["G","F"],u:2},
{n:"Joud",o:"Arabic",m:"Generosity of spirit",s:1,t:["V","F"],u:3},
{n:"Khadija",o:"Arabic",m:"First wife of Prophet, early baby",s:3,t:["F","S"],u:1},
{n:"Lama",o:"Arabic",m:"Lips dark with beauty",s:2,t:["E","N"],u:3},
{n:"Layan",o:"Arabic",m:"Gentle, soft",s:2,t:["E","V"],u:2},
{n:"Layla",o:"Arabic",m:"Night beauty",s:2,t:["N","E"],u:1},
{n:"Lina",o:"Arabic",m:"Tender, palm tree",s:2,t:["N","V"],u:2},
{n:"Lubna",o:"Arabic",m:"Storax tree, sweetness",s:2,t:["N","V"],u:2},
{n:"Lujain",o:"Arabic",m:"Silver, precious",s:2,t:["L","E"],u:2},
{n:"Maha",o:"Arabic",m:"Wild cow eyes, beauty",s:2,t:["N","E"],u:2},
{n:"Manal",o:"Arabic",m:"Attainment, achievement",s:2,t:["S","W"],u:2},
{n:"Marwa",o:"Arabic",m:"Sacred hill, flint stone",s:2,t:["F","N"],u:2},
{n:"Maryam",o:"Arabic",m:"Beloved, sea of sorrow",s:3,t:["F","G"],u:1},
{n:"Maysa",o:"Arabic",m:"Walking with pride",s:2,t:["E","S"],u:2},
{n:"Mira",o:"Arabic",m:"Provisions, admirable",s:2,t:["G","E"],u:2},
{n:"Mona",o:"Arabic",m:"Wish, desire",s:2,t:["H","V"],u:2},
{n:"Nada",o:"Arabic",m:"Dew, generosity",s:2,t:["N","G"],u:2},
{n:"Najwa",o:"Arabic",m:"Confidential talk, whisper",s:2,t:["V","E"],u:2},
{n:"Noor",o:"Arabic",m:"Divine light",s:1,t:["L","F"],u:1},
{n:"Nouf",o:"Arabic",m:"Highest point",s:1,t:["S","N"],u:3},
{n:"Rand",o:"Arabic",m:"Fragrant tree",s:1,t:["N","E"],u:3},
{n:"Rana",o:"Arabic",m:"Gazing, beautiful",s:2,t:["E","N"],u:2},
{n:"Rawda",o:"Arabic",m:"Garden, meadow",s:2,t:["N","H"],u:2},
{n:"Rawan",o:"Arabic",m:"Fluent, easy-going",s:2,t:["E","R"],u:2},
{n:"Razan",o:"Arabic",m:"Calm, composed",s:2,t:["W","E"],u:2},
{n:"Reem",o:"Arabic",m:"White antelope",s:1,t:["N","E"],u:2},
{n:"Reham",o:"Arabic",m:"Gentle rain",s:2,t:["N","V"],u:3},
{n:"Rima",o:"Arabic",m:"White antelope, graceful",s:2,t:["N","E"],u:2},
{n:"Ruba",o:"Arabic",m:"Hills, beautiful heights",s:2,t:["N","E"],u:2},
{n:"Saba",o:"Arabic",m:"Morning breeze",s:2,t:["N","R"],u:2},
{n:"Sabah",o:"Arabic",m:"Morning light",s:2,t:["L","H"],u:2},
{n:"Sabreen",o:"Arabic",m:"Patient, enduring",s:3,t:["S","F"],u:2},
{n:"Safa",o:"Arabic",m:"Pure, clarity",s:2,t:["F","L"],u:2},
{n:"Salma",o:"Arabic",m:"Peaceful, safe",s:2,t:["F","V"],u:2},
{n:"Sama",o:"Arabic",m:"Sky, heaven",s:2,t:["L","G"],u:2},
{n:"Samar",o:"Arabic",m:"Fruit, evening conversation",s:2,t:["N","V"],u:2},
{n:"Samira",o:"Arabic",m:"Entertaining companion",s:3,t:["V","W"],u:2},
{n:"Sana",o:"Arabic",m:"Radiance, brilliance",s:2,t:["L","E"],u:2},
{n:"Sara",o:"Arabic",m:"Pure, noble",s:2,t:["F","E"],u:1},
{n:"Shahd",o:"Arabic",m:"Honey, sweet",s:1,t:["V","N"],u:2},
{n:"Shoug",o:"Arabic",m:"Longing, passion",s:1,t:["V","R"],u:3},
{n:"Tasneem",o:"Arabic",m:"Spring of paradise",s:3,t:["G","N"],u:2},
{n:"Wafa",o:"Arabic",m:"Loyalty, faithfulness",s:2,t:["F","V"],u:2},
{n:"Widad",o:"Arabic",m:"Friendship, affection",s:2,t:["V","F"],u:3},
{n:"Yara",o:"Arabic",m:"Small butterfly, water lady",s:2,t:["N","R"],u:2},
{n:"Yasmin",o:"Arabic",m:"Jasmine flower",s:3,t:["N","E"],u:1},
{n:"Yusra",o:"Arabic",m:"Ease, prosperity",s:2,t:["H","G"],u:2},
{n:"Zainab",o:"Arabic",m:"Fragrant flowering tree",s:3,t:["N","F"],u:1},
{n:"Zahra",o:"Arabic",m:"Luminous, flower",s:2,t:["L","N"],u:2},
{n:"Zara",o:"Arabic",m:"Radiance, princess",s:2,t:["L","E"],u:1},
{n:"Abeer",o:"Arabic",m:"Fragrance, perfume",s:2,t:["N","E"],u:3},
{n:"Ahd",o:"Arabic",m:"Pledge, covenant",s:1,t:["F","S"],u:4},
{n:"Amal",o:"Arabic",m:"Hope, aspiration",s:2,t:["H","F"],u:2},
{n:"Aseel",o:"Arabic",m:"Original, authentic",s:2,t:["E","W"],u:3},
{n:"Bayan",o:"Arabic",m:"Clarity, eloquence",s:2,t:["W","E"],u:2},
{n:"Dua",o:"Arabic",m:"Prayer, supplication",s:2,t:["F","G"],u:2},
{n:"Ghalia",o:"Arabic",m:"Precious, dear",s:3,t:["V","E"],u:2},
{n:"Hiam",o:"Arabic",m:"Love, passion",s:2,t:["V","R"],u:3},
{n:"Jinan",o:"Arabic",m:"Gardens of paradise",s:2,t:["G","N"],u:3},
{n:"Malak",o:"Arabic",m:"Angel, messenger",s:2,t:["F","G"],u:2},
{n:"Raghad",o:"Arabic",m:"Plentiful, comfortable",s:2,t:["H","V"],u:2},
{n:"Rahaf",o:"Arabic",m:"Delicate, gentle",s:2,t:["E","V"],u:2},
{n:"Raneem",o:"Arabic",m:"Singing, melody",s:2,t:["V","R"],u:2},
{n:"Rasha",o:"Arabic",m:"Young gazelle",s:2,t:["N","E"],u:2},
{n:"Rayan",o:"Arabic",m:"Lush, watered",s:2,t:["N","H"],u:2},
{n:"Sedra",o:"Arabic",m:"Cedar tree",s:2,t:["N","S"],u:3},
{n:"Shahed",o:"Arabic",m:"Witness, honey",s:2,t:["F","V"],u:2},
{n:"Shams",o:"Arabic",m:"Sun",s:1,t:["L","S"],u:2},
{n:"Taghreed",o:"Arabic",m:"Singing of birds",s:3,t:["N","R"],u:3},
{n:"Tahani",o:"Arabic",m:"Congratulations, best wishes",s:3,t:["V","H"],u:2},
{n:"Taleen",o:"Arabic",m:"Singing bird",s:2,t:["N","R"],u:3},
{n:"Tamara",o:"Arabic",m:"Date palm, spice",s:3,t:["N","E"],u:2},
{n:"Tuqa",o:"Arabic",m:"Piety, devoutness",s:2,t:["F","G"],u:3},
{n:"Warda",o:"Arabic",m:"Rose flower",s:2,t:["N","V"],u:2},
{n:"Wijdan",o:"Arabic",m:"Sentiment, emotion",s:2,t:["V","W"],u:3},
{n:"Bushra",o:"Arabic",m:"Good news, glad tidings",s:2,t:["H","G"],u:2},
{n:"Dalia",o:"Arabic",m:"Gentle, tender branch",s:3,t:["N","E"],u:2},
{n:"Enas",o:"Arabic",m:"Sociability, friendliness",s:2,t:["V","W"],u:2},
{n:"Fajr",o:"Arabic",m:"Dawn, beginning",s:1,t:["L","H"],u:3},
{n:"Ghazal",o:"Arabic",m:"Gazelle, love poem",s:2,t:["N","V"],u:2},
{n:"Hala",o:"Arabic",m:"Halo of moon, sweetness",s:2,t:["L","E"],u:2},
{n:"Halima",o:"Arabic",m:"Gentle, mild",s:3,t:["V","E"],u:2},
{n:"Hanan",o:"Arabic",m:"Compassion, affection",s:2,t:["V","F"],u:2},
{n:"Heba",o:"Arabic",m:"Gift, donation",s:2,t:["G","V"],u:2},
{n:"Iman",o:"Arabic",m:"Faith, belief",s:2,t:["F","G"],u:2},
{n:"Isra",o:"Arabic",m:"Night journey",s:2,t:["R","F"],u:2},
{n:"Kanza",o:"Arabic",m:"Treasure, hidden wealth",s:2,t:["G","E"],u:3},
{n:"Lana",o:"Arabic",m:"Tender, gentle",s:2,t:["E","V"],u:2},
{n:"Lara",o:"Arabic",m:"Cheerful, famous",s:2,t:["H","E"],u:2},
{n:"Leila",o:"Arabic",m:"Dark beauty of night",s:3,t:["N","E"],u:1},
{n:"Loujayn",o:"Arabic",m:"Silver",s:2,t:["L","E"],u:2},
{n:"Manar",o:"Arabic",m:"Lighthouse, guiding light",s:2,t:["L","W"],u:2},
{n:"Nahla",o:"Arabic",m:"Drink of water, gift",s:2,t:["G","N"],u:2},
{n:"Naima",o:"Arabic",m:"Living in ease, blessed",s:3,t:["G","H"],u:2},
{n:"Nesma",o:"Arabic",m:"Breeze, gentle wind",s:2,t:["N","R"],u:2},
{n:"Nida",o:"Arabic",m:"Call, voice",s:2,t:["R","F"],u:2},
{n:"Noura",o:"Arabic",m:"Light, luminous",s:2,t:["L","F"],u:2},
{n:"Ola",o:"Arabic",m:"Elevated, supreme",s:2,t:["S","E"],u:2},
{n:"Randa",o:"Arabic",m:"Scented tree",s:2,t:["N","E"],u:2},
{n:"Saja",o:"Arabic",m:"Calm, still waters",s:2,t:["E","N"],u:3},
{n:"Salam",o:"Arabic",m:"Peace, safety",s:2,t:["F","V"],u:2},
{n:"Samah",o:"Arabic",m:"Forgiveness, generosity",s:2,t:["V","F"],u:2},
{n:"Sawsan",o:"Arabic",m:"Lily of the valley",s:2,t:["N","E"],u:2},
{n:"Sereen",o:"Arabic",m:"Serene, calm",s:2,t:["E","W"],u:2},
{n:"Shaimaa",o:"Arabic",m:"Good character",s:3,t:["E","W"],u:2},
{n:"Shuruq",o:"Arabic",m:"Sunrise",s:2,t:["L","H"],u:2},
{n:"Sultana",o:"Arabic",m:"Queen, ruler",s:3,t:["S","E"],u:2},
{n:"Tala",o:"Arabic",m:"Young palm tree",s:2,t:["N","E"],u:2},
{n:"Tasnim",o:"Arabic",m:"Fountain in paradise",s:2,t:["G","N"],u:2},
{n:"Walaa",o:"Arabic",m:"Loyalty, devotion",s:2,t:["F","V"],u:2},
{n:"Wissam",o:"Arabic",m:"Medal of honor, badge",s:2,t:["S","E"],u:3},
{n:"Yasmine",o:"Arabic",m:"Jasmine, fragrant flower",s:3,t:["N","E"],u:1},
{n:"Zahraa",o:"Arabic",m:"The bright flower",s:2,t:["L","N"],u:2},
{n:"Zinah",o:"Arabic",m:"Beauty, adornment",s:2,t:["E","N"],u:3},
{n:"Ada",o:"English",m:"Noble, kind",s:2,t:["E","S"],u:2},
{n:"Adelaide",o:"English",m:"Noble, kind",s:4,t:["E","S"],u:2},
{n:"Alice",o:"English",m:"Noble, truthful",s:2,t:["E","W"],u:1},
{n:"Amber",o:"English",m:"Jewel, golden resin",s:2,t:["N","L"],u:1},
{n:"Amelia",o:"English",m:"Work, industrious",s:4,t:["S","E"],u:1},
{n:"Arabella",o:"English",m:"Yielding to prayer",s:4,t:["F","E"],u:2},
{n:"Audrey",o:"English",m:"Noble strength",s:2,t:["S","E"],u:2},
{n:"Aurora",o:"English",m:"Dawn, new beginnings",s:3,t:["L","H"],u:2},
{n:"Autumn",o:"English",m:"Season of harvest",s:2,t:["N","H"],u:2},
{n:"Ava",o:"English",m:"Like a bird, life",s:2,t:["N","R"],u:1},
{n:"Beatrice",o:"English",m:"She who brings happiness",s:3,t:["V","H"],u:2},
{n:"Belle",o:"English",m:"Beautiful",s:1,t:["E","V"],u:2},
{n:"Bridget",o:"English",m:"Strength, virtue",s:2,t:["S","F"],u:2},
{n:"Brooke",o:"English",m:"Small stream",s:1,t:["N","R"],u:2},
{n:"Cara",o:"English",m:"Beloved, dear",s:2,t:["V","E"],u:2},
{n:"Charlotte",o:"English",m:"Free woman",s:3,t:["R","E"],u:1},
{n:"Clara",o:"English",m:"Bright, clear",s:2,t:["L","E"],u:2},
{n:"Clementine",o:"English",m:"Gentle, merciful",s:4,t:["V","E"],u:3},
{n:"Cora",o:"English",m:"Heart, maiden",s:2,t:["V","E"],u:2},
{n:"Daisy",o:"English",m:"Day's eye, innocence",s:2,t:["N","V"],u:2},
{n:"Diana",o:"English",m:"Divine, luminous",s:3,t:["L","S"],u:2},
{n:"Dorothy",o:"English",m:"Gift of God",s:3,t:["G","F"],u:2},
{n:"Eden",o:"English",m:"Delight, paradise",s:2,t:["G","N"],u:2},
{n:"Eleanor",o:"English",m:"Shining one, bright",s:3,t:["L","E"],u:2},
{n:"Elena",o:"English",m:"Shining light",s:3,t:["L","E"],u:2},
{n:"Eliza",o:"English",m:"My God is abundance",s:3,t:["F","E"],u:2},
{n:"Ella",o:"English",m:"Fairy maiden, all",s:2,t:["E","V"],u:1},
{n:"Emily",o:"English",m:"Rival, industrious",s:3,t:["S","E"],u:1},
{n:"Emma",o:"English",m:"Whole, universal",s:2,t:["E","V"],u:1},
{n:"Eva",o:"English",m:"Life, living",s:2,t:["H","N"],u:2},
{n:"Faith",o:"English",m:"Trust, belief",s:1,t:["F","G"],u:2},
{n:"Faye",o:"English",m:"Fairy, faith",s:1,t:["R","F"],u:2},
{n:"Fern",o:"English",m:"A feathery plant",s:1,t:["N","R"],u:2},
{n:"Fiona",o:"English",m:"White, fair",s:3,t:["E","N"],u:2},
{n:"Florence",o:"English",m:"Flourishing, prosperous",s:2,t:["H","N"],u:2},
{n:"Freya",o:"English",m:"Noble woman, goddess",s:2,t:["S","E"],u:2},
{n:"Grace",o:"English",m:"Divine grace, goodness",s:1,t:["F","G"],u:1},
{n:"Hannah",o:"English",m:"Grace of God",s:2,t:["G","F"],u:1},
{n:"Harper",o:"English",m:"Harp player",s:2,t:["R","E"],u:2},
{n:"Hazel",o:"English",m:"Hazel tree, wisdom",s:2,t:["N","W"],u:2},
{n:"Helen",o:"English",m:"Shining, bright",s:2,t:["L","E"],u:2},
{n:"Holly",o:"English",m:"Holly tree",s:2,t:["N","E"],u:2},
{n:"Hope",o:"English",m:"Hope, aspiration",s:1,t:["H","F"],u:2},
{n:"Imogen",o:"English",m:"Maiden, innocent",s:3,t:["E","V"],u:2},
{n:"Iris",o:"English",m:"Rainbow, messenger",s:2,t:["L","N"],u:2},
{n:"Ivy",o:"English",m:"Climbing vine, fidelity",s:2,t:["N","F"],u:2},
{n:"Jade",o:"English",m:"Green gemstone",s:1,t:["N","E"],u:2},
{n:"Jasmine",o:"English",m:"Jasmine flower",s:3,t:["N","E"],u:2},
{n:"Joy",o:"English",m:"Happiness",s:1,t:["V","H"],u:2},
{n:"Kate",o:"English",m:"Pure, clear",s:1,t:["F","E"],u:2},
{n:"Katherine",o:"English",m:"Pure, clear",s:3,t:["F","E"],u:1},
{n:"Laura",o:"English",m:"Laurel tree, victory",s:2,t:["N","S"],u:2},
{n:"Leah",o:"English",m:"Weary, meadow",s:2,t:["N","E"],u:2},
{n:"Lily",o:"English",m:"Lily flower, purity",s:2,t:["N","F"],u:1},
{n:"Louise",o:"English",m:"Famous warrior",s:2,t:["S","E"],u:2},
{n:"Lucy",o:"English",m:"Light",s:2,t:["L","E"],u:1},
{n:"Lydia",o:"English",m:"From Lydia, noble",s:3,t:["E","S"],u:2},
{n:"Mabel",o:"English",m:"Lovable",s:2,t:["V","E"],u:3},
{n:"Matilda",o:"English",m:"Strength in battle",s:3,t:["S","E"],u:2},
{n:"Maya",o:"English",m:"Water, illusion",s:2,t:["N","W"],u:2},
{n:"Mia",o:"English",m:"Mine, beloved",s:2,t:["V","E"],u:1},
{n:"Molly",o:"English",m:"Star of the sea",s:2,t:["L","N"],u:2},
{n:"Morgan",o:"English",m:"Sea-born, great brightness",s:2,t:["N","L"],u:2},
{n:"Naomi",o:"English",m:"Pleasant, beautiful",s:3,t:["E","V"],u:2},
{n:"Natalie",o:"English",m:"Born on Christmas, birthday",s:3,t:["H","F"],u:2},
{n:"Nora",o:"English",m:"Honor, light",s:2,t:["L","E"],u:2},
{n:"Olive",o:"English",m:"Olive tree, peace",s:2,t:["N","F"],u:2},
{n:"Olivia",o:"English",m:"Olive tree, peace",s:4,t:["N","F"],u:1},
{n:"Penelope",o:"English",m:"Weaver, faithful",s:4,t:["F","W"],u:2},
{n:"Phoebe",o:"English",m:"Bright, shining",s:2,t:["L","E"],u:2},
{n:"Poppy",o:"English",m:"Poppy flower",s:2,t:["N","H"],u:2},
{n:"Rachel",o:"English",m:"Innocent lamb",s:2,t:["F","V"],u:2},
{n:"Rebecca",o:"English",m:"To bind, captivating",s:3,t:["E","V"],u:2},
{n:"Rose",o:"English",m:"Rose flower",s:1,t:["N","V"],u:2},
{n:"Ruby",o:"English",m:"Red gemstone",s:2,t:["N","E"],u:2},
{n:"Sadie",o:"English",m:"Princess",s:2,t:["E","S"],u:2},
{n:"Scarlett",o:"English",m:"Red, bright",s:2,t:["L","E"],u:2},
{n:"Selena",o:"English",m:"Moon",s:3,t:["L","N"],u:2},
{n:"Skye",o:"English",m:"Sky, free",s:1,t:["R","N"],u:2},
{n:"Sofia",o:"English",m:"Wisdom",s:3,t:["W","E"],u:1},
{n:"Sophie",o:"English",m:"Wisdom",s:2,t:["W","E"],u:1},
{n:"Stella",o:"English",m:"Star",s:2,t:["L","E"],u:2},
{n:"Summer",o:"English",m:"Summer season",s:2,t:["N","H"],u:2},
{n:"Violet",o:"English",m:"Violet flower",s:3,t:["N","E"],u:2},
{n:"Willow",o:"English",m:"Willow tree, graceful",s:2,t:["N","E"],u:2},
{n:"Wren",o:"English",m:"Small bird",s:1,t:["N","R"],u:2},
{n:"Zoe",o:"English",m:"Life",s:2,t:["H","N"],u:2},
{n:"Aria",o:"English",m:"Air, song, melody",s:3,t:["R","E"],u:2},
{n:"Ember",o:"English",m:"Burning coal, warmth",s:2,t:["L","V"],u:3},
{n:"Haven",o:"English",m:"Safe place, refuge",s:2,t:["F","G"],u:3},
{n:"Juniper",o:"English",m:"Juniper tree",s:3,t:["N","R"],u:3},
{n:"Luna",o:"English",m:"Moon",s:2,t:["L","N"],u:2},
{n:"Lyra",o:"English",m:"Lyre constellation",s:2,t:["L","N"],u:3},
{n:"Nova",o:"English",m:"New, star explosion",s:2,t:["L","H"],u:3},
{n:"Quinn",o:"English",m:"Wisdom, intelligence",s:1,t:["W","S"],u:2},
{n:"Riley",o:"English",m:"Courageous, rye clearing",s:2,t:["S","N"],u:2},
{n:"River",o:"English",m:"Flowing water",s:2,t:["N","R"],u:3},
{n:"Rowan",o:"English",m:"Rowan tree, red",s:2,t:["N","S"],u:2},
{n:"Sage",o:"English",m:"Herb, wise person",s:1,t:["W","N"],u:2},
{n:"Serenity",o:"English",m:"Peaceful, calm",s:4,t:["F","E"],u:2},
{n:"Winter",o:"English",m:"Winter season",s:2,t:["N","E"],u:3},
{n:"Alba",o:"Latin",m:"Dawn, white",s:2,t:["L","H"],u:3},
{n:"Amanda",o:"Latin",m:"Worthy of love",s:3,t:["V","E"],u:2},
{n:"Beatrix",o:"Latin",m:"She who brings joy",s:3,t:["V","H"],u:3},
{n:"Cecilia",o:"Latin",m:"Blind, heavenly",s:4,t:["F","E"],u:2},
{n:"Clara",o:"Latin",m:"Bright, clear, famous",s:2,t:["L","E"],u:2},
{n:"Emilia",o:"Latin",m:"Rival, industrious",s:4,t:["S","E"],u:2},
{n:"Felicity",o:"Latin",m:"Happiness, good luck",s:4,t:["H","V"],u:2},
{n:"Flora",o:"Latin",m:"Flower, flowering",s:2,t:["N","E"],u:2},
{n:"Gemma",o:"Latin",m:"Precious stone, gem",s:2,t:["E","N"],u:2},
{n:"Gloria",o:"Latin",m:"Glory, praise",s:3,t:["S","L"],u:2},
{n:"Helena",o:"Latin",m:"Bright, shining",s:3,t:["L","E"],u:2},
{n:"Honor",o:"Latin",m:"Honor, dignity",s:2,t:["S","F"],u:2},
{n:"Julia",o:"Latin",m:"Youthful, sky father",s:3,t:["E","H"],u:2},
{n:"Lavinia",o:"Latin",m:"Purity, woman of Rome",s:4,t:["F","E"],u:3},
{n:"Leona",o:"Latin",m:"Lioness, brave",s:3,t:["S","E"],u:2},
{n:"Lucinda",o:"Latin",m:"Light, illuminated",s:3,t:["L","E"],u:3},
{n:"Maria",o:"Latin",m:"Star of the sea, beloved",s:3,t:["L","F"],u:1},
{n:"Natalia",o:"Latin",m:"Born on Christmas",s:4,t:["H","F"],u:2},
{n:"Octavia",o:"Latin",m:"Eighth, born eighth",s:4,t:["E","S"],u:3},
{n:"Regina",o:"Latin",m:"Queen",s:3,t:["S","E"],u:2},
{n:"Rosa",o:"Latin",m:"Rose, beautiful",s:2,t:["N","V"],u:2},
{n:"Serena",o:"Latin",m:"Serene, calm, peaceful",s:3,t:["E","F"],u:2},
{n:"Sylvia",o:"Latin",m:"Forest, woods",s:3,t:["N","R"],u:2},
{n:"Valentina",o:"Latin",m:"Strong, brave, healthy",s:4,t:["S","V"],u:2},
{n:"Vera",o:"Latin",m:"Truth, faith",s:2,t:["F","W"],u:2},
{n:"Victoria",o:"Latin",m:"Victory, conqueror",s:4,t:["S","H"],u:2},
{n:"Viola",o:"Latin",m:"Violet flower",s:3,t:["N","E"],u:3},
{n:"Vivienne",o:"Latin",m:"Alive, lively",s:3,t:["H","E"],u:3},
{n:"Celia",o:"Latin",m:"Heavenly, celestial",s:3,t:["L","F"],u:3},
{n:"Camilla",o:"Latin",m:"Temple servant, noble",s:3,t:["F","E"],u:2},
{n:"Stella",o:"Latin",m:"Star",s:2,t:["L","E"],u:2},
{n:"Alexia",o:"Greek",m:"Defender, helper",s:4,t:["S","F"],u:2},
{n:"Anastasia",o:"Greek",m:"Resurrection, rebirth",s:5,t:["H","F"],u:2},
{n:"Anthea",o:"Greek",m:"Flower, blossom",s:3,t:["N","E"],u:3},
{n:"Callie",o:"Greek",m:"Beautiful",s:2,t:["E","V"],u:2},
{n:"Chloe",o:"Greek",m:"Blooming, fertility",s:2,t:["N","H"],u:1},
{n:"Daphne",o:"Greek",m:"Laurel tree, victory",s:2,t:["N","S"],u:2},
{n:"Elena",o:"Greek",m:"Shining light",s:3,t:["L","E"],u:2},
{n:"Evangeline",o:"Greek",m:"Bearer of good news",s:4,t:["G","F"],u:3},
{n:"Helena",o:"Greek",m:"Torch, moon, bright",s:3,t:["L","E"],u:2},
{n:"Irene",o:"Greek",m:"Peace",s:3,t:["F","V"],u:2},
{n:"Katerina",o:"Greek",m:"Pure, clear",s:4,t:["F","E"],u:2},
{n:"Melissa",o:"Greek",m:"Honey bee",s:3,t:["N","V"],u:2},
{n:"Phoebe",o:"Greek",m:"Bright, shining",s:2,t:["L","E"],u:2},
{n:"Rhea",o:"Greek",m:"Flowing, ease",s:2,t:["N","E"],u:2},
{n:"Selene",o:"Greek",m:"Moon goddess",s:3,t:["L","N"],u:3},
{n:"Sophia",o:"Greek",m:"Wisdom",s:3,t:["W","E"],u:1},
{n:"Thalia",o:"Greek",m:"To flourish, blooming",s:3,t:["N","H"],u:3},
{n:"Theodora",o:"Greek",m:"Gift of God",s:4,t:["G","F"],u:3},
{n:"Thea",o:"Greek",m:"Goddess, divine gift",s:2,t:["G","F"],u:2},
{n:"Vanessa",o:"Greek",m:"Butterfly",s:3,t:["N","R"],u:2},
{n:"Zoe",o:"Greek",m:"Life",s:2,t:["H","N"],u:2},
{n:"Azadeh",o:"Persian",m:"Free, noble",s:3,t:["R","S"],u:3},
{n:"Bahar",o:"Persian",m:"Spring season",s:2,t:["N","H"],u:2},
{n:"Dana",o:"Persian",m:"Wise, knowledgeable",s:2,t:["W","E"],u:2},
{n:"Darya",o:"Persian",m:"Sea, ocean",s:3,t:["N","S"],u:3},
{n:"Delara",o:"Persian",m:"Adorning the heart",s:3,t:["V","E"],u:3},
{n:"Elnaz",o:"Persian",m:"Noble lady",s:2,t:["E","S"],u:3},
{n:"Laleh",o:"Persian",m:"Tulip flower",s:2,t:["N","E"],u:3},
{n:"Leila",o:"Persian",m:"Night, dark-haired",s:3,t:["N","E"],u:1},
{n:"Mahsa",o:"Persian",m:"Like the moon",s:2,t:["L","E"],u:2},
{n:"Nasim",o:"Persian",m:"Gentle breeze",s:2,t:["N","R"],u:2},
{n:"Nasrin",o:"Persian",m:"Wild rose",s:2,t:["N","E"],u:2},
{n:"Negar",o:"Persian",m:"Sweetheart, idol",s:2,t:["V","E"],u:3},
{n:"Nika",o:"Persian",m:"Good, kind",s:2,t:["V","F"],u:3},
{n:"Niloufar",o:"Persian",m:"Lotus flower",s:3,t:["N","E"],u:3},
{n:"Parisa",o:"Persian",m:"Like a fairy",s:3,t:["E","R"],u:3},
{n:"Parvin",o:"Persian",m:"Pleiades, cluster of stars",s:2,t:["L","N"],u:3},
{n:"Raha",o:"Persian",m:"Free, comfortable",s:2,t:["R","H"],u:3},
{n:"Roya",o:"Persian",m:"Dream, vision",s:2,t:["R","H"],u:2},
{n:"Sanam",o:"Persian",m:"Beloved, sweetheart",s:2,t:["V","E"],u:2},
{n:"Setareh",o:"Persian",m:"Star",s:3,t:["L","N"],u:3},
{n:"Shirin",o:"Persian",m:"Sweet, pleasant",s:2,t:["V","E"],u:2},
{n:"Soraya",o:"Persian",m:"Pleiades star cluster",s:3,t:["L","N"],u:2},
{n:"Mina",o:"Persian",m:"Blue sky, gem, love",s:2,t:["L","V"],u:2},
{n:"Roxana",o:"Persian",m:"Bright, dawn",s:3,t:["L","E"],u:2},
{n:"Anahita",o:"Persian",m:"Goddess of water and fertility",s:4,t:["N","G"],u:3},
{n:"Adele",o:"French",m:"Noble, kind",s:2,t:["E","S"],u:2},
{n:"Amelie",o:"French",m:"Hardworking, industrious",s:3,t:["S","E"],u:2},
{n:"Anais",o:"French",m:"Grace",s:2,t:["E","F"],u:3},
{n:"Blanche",o:"French",m:"White, pure",s:1,t:["F","E"],u:3},
{n:"Camille",o:"French",m:"Perfect, unblemished",s:2,t:["F","E"],u:2},
{n:"Celine",o:"French",m:"Moon, heaven",s:2,t:["L","F"],u:2},
{n:"Charlotte",o:"French",m:"Free woman",s:3,t:["R","E"],u:1},
{n:"Claire",o:"French",m:"Clear, bright",s:1,t:["L","E"],u:2},
{n:"Clementine",o:"French",m:"Merciful, gentle",s:4,t:["V","E"],u:3},
{n:"Colette",o:"French",m:"Victory of the people",s:2,t:["S","E"],u:3},
{n:"Delphine",o:"French",m:"Dolphin, woman from Delphi",s:2,t:["N","E"],u:3},
{n:"Elodie",o:"French",m:"Wealthy, blessed",s:3,t:["G","E"],u:3},
{n:"Eloise",o:"French",m:"Healthy, wide",s:3,t:["H","E"],u:3},
{n:"Estelle",o:"French",m:"Star",s:2,t:["L","E"],u:3},
{n:"Fleur",o:"French",m:"Flower",s:1,t:["N","E"],u:3},
{n:"Isabelle",o:"French",m:"Devoted to God",s:3,t:["F","G"],u:2},
{n:"Juliette",o:"French",m:"Youthful",s:3,t:["E","H"],u:2},
{n:"Lea",o:"French",m:"Weary, meadow",s:2,t:["N","E"],u:2},
{n:"Louise",o:"French",m:"Famous warrior",s:2,t:["S","E"],u:2},
{n:"Lucie",o:"French",m:"Light",s:2,t:["L","E"],u:2},
{n:"Manon",o:"French",m:"Bitter, beloved",s:2,t:["V","E"],u:3},
{n:"Marine",o:"French",m:"Of the sea",s:2,t:["N","R"],u:2},
{n:"Mathilde",o:"French",m:"Strength in battle",s:2,t:["S","E"],u:2},
{n:"Melanie",o:"French",m:"Dark, black",s:3,t:["E","N"],u:2},
{n:"Noemie",o:"French",m:"Pleasant, beautiful",s:3,t:["E","V"],u:3},
{n:"Pauline",o:"French",m:"Small, humble",s:2,t:["E","F"],u:2},
{n:"Roxane",o:"French",m:"Dawn, bright",s:2,t:["L","E"],u:3},
{n:"Sabine",o:"French",m:"Sabine woman",s:2,t:["E","S"],u:3},
{n:"Sophie",o:"French",m:"Wisdom",s:2,t:["W","E"],u:1},
{n:"Sylvie",o:"French",m:"Forest, woods",s:2,t:["N","R"],u:3},
{n:"Violette",o:"French",m:"Violet flower",s:3,t:["N","E"],u:3},
{n:"Alessia",o:"Italian",m:"Defender",s:4,t:["S","E"],u:2},
{n:"Angelica",o:"Italian",m:"Angel, messenger",s:4,t:["F","E"],u:2},
{n:"Aurora",o:"Italian",m:"Dawn",s:3,t:["L","H"],u:2},
{n:"Beatrice",o:"Italian",m:"She who brings joy",s:3,t:["V","H"],u:2},
{n:"Bianca",o:"Italian",m:"White, pure",s:3,t:["F","E"],u:2},
{n:"Camilla",o:"Italian",m:"Temple servant",s:3,t:["F","E"],u:2},
{n:"Chiara",o:"Italian",m:"Bright, clear",s:3,t:["L","E"],u:2},
{n:"Elisa",o:"Italian",m:"Devoted to God",s:3,t:["F","G"],u:2},
{n:"Fiamma",o:"Italian",m:"Flame, fire",s:3,t:["L","S"],u:3},
{n:"Francesca",o:"Italian",m:"Free, from France",s:3,t:["R","E"],u:2},
{n:"Gabriella",o:"Italian",m:"God is my strength",s:4,t:["G","S"],u:2},
{n:"Ginevra",o:"Italian",m:"White wave, juniper",s:3,t:["N","E"],u:3},
{n:"Giulia",o:"Italian",m:"Youthful",s:3,t:["E","H"],u:2},
{n:"Isabella",o:"Italian",m:"Devoted to God",s:4,t:["F","G"],u:1},
{n:"Lucia",o:"Italian",m:"Light",s:3,t:["L","E"],u:2},
{n:"Martina",o:"Italian",m:"Of Mars, warrior",s:3,t:["S","E"],u:2},
{n:"Sara",o:"Italian",m:"Princess, pure",s:2,t:["F","E"],u:1},
{n:"Serena",o:"Italian",m:"Serene, calm",s:3,t:["E","F"],u:2},
{n:"Sofia",o:"Italian",m:"Wisdom",s:3,t:["W","E"],u:1},
{n:"Valentina",o:"Italian",m:"Strong, healthy",s:4,t:["S","V"],u:2},
{n:"Veronica",o:"Italian",m:"True image",s:4,t:["F","W"],u:2},
{n:"Vittoria",o:"Italian",m:"Victory",s:4,t:["S","H"],u:2},
{n:"Ornella",o:"Italian",m:"Flowering ash tree",s:3,t:["N","E"],u:3},
{n:"Aoife",o:"Celtic / Irish",m:"Beautiful, radiant",s:2,t:["E","L"],u:3},
{n:"Aine",o:"Celtic / Irish",m:"Radiance, brilliance",s:2,t:["L","E"],u:3},
{n:"Brigid",o:"Celtic / Irish",m:"Strength, virtue",s:2,t:["S","F"],u:3},
{n:"Caoimhe",o:"Celtic / Irish",m:"Gentle, beautiful",s:2,t:["E","V"],u:3},
{n:"Ciara",o:"Celtic / Irish",m:"Dark, black",s:2,t:["N","E"],u:2},
{n:"Erin",o:"Celtic / Irish",m:"Ireland, peace",s:2,t:["F","N"],u:2},
{n:"Imogen",o:"Celtic / Irish",m:"Maiden, innocent",s:3,t:["E","V"],u:2},
{n:"Maeve",o:"Celtic / Irish",m:"Intoxicating, she who rules",s:1,t:["S","E"],u:2},
{n:"Niamh",o:"Celtic / Irish",m:"Bright, radiant",s:1,t:["L","E"],u:3},
{n:"Orla",o:"Celtic / Irish",m:"Golden princess",s:2,t:["L","E"],u:3},
{n:"Roisin",o:"Celtic / Irish",m:"Little rose",s:2,t:["N","V"],u:3},
{n:"Saoirse",o:"Celtic / Irish",m:"Freedom, liberty",s:2,t:["R","S"],u:3},
{n:"Siobhan",o:"Celtic / Irish",m:"God is gracious",s:2,t:["G","F"],u:3},
{n:"Sorcha",o:"Celtic / Irish",m:"Bright, radiant",s:2,t:["L","E"],u:3},
{n:"Tara",o:"Celtic / Irish",m:"Hill, tower",s:2,t:["S","N"],u:2},
{n:"Alanna",o:"Celtic / Irish",m:"Little rock, harmony",s:3,t:["N","V"],u:2},
{n:"Keira",o:"Celtic / Irish",m:"Dark one",s:2,t:["E","N"],u:2},
{n:"Moira",o:"Celtic / Irish",m:"Fate, destiny",s:2,t:["F","W"],u:3},
{n:"Shannon",o:"Celtic / Irish",m:"Old river",s:2,t:["N","W"],u:2},
{n:"Nuala",o:"Celtic / Irish",m:"Fair shoulder",s:2,t:["E","N"],u:4},
{n:"Una",o:"Celtic / Irish",m:"Lamb, unity",s:2,t:["F","V"],u:3},
{n:"Astrid",o:"Scandinavian",m:"Divinely beautiful",s:2,t:["E","L"],u:2},
{n:"Elsa",o:"Scandinavian",m:"Noble, God is my oath",s:2,t:["S","F"],u:2},
{n:"Freya",o:"Scandinavian",m:"Goddess of love, beauty",s:2,t:["V","E"],u:2},
{n:"Frida",o:"Scandinavian",m:"Peace, love",s:2,t:["F","V"],u:2},
{n:"Hanna",o:"Scandinavian",m:"Grace of God",s:2,t:["G","F"],u:2},
{n:"Helga",o:"Scandinavian",m:"Holy, blessed",s:2,t:["F","S"],u:3},
{n:"Ida",o:"Scandinavian",m:"Hardworking",s:2,t:["S","E"],u:2},
{n:"Ingrid",o:"Scandinavian",m:"Beautiful, beloved",s:2,t:["E","V"],u:2},
{n:"Linnea",o:"Scandinavian",m:"Linden tree, lime tree",s:3,t:["N","E"],u:3},
{n:"Maja",o:"Scandinavian",m:"Pearl, great",s:2,t:["E","N"],u:2},
{n:"Maren",o:"Scandinavian",m:"Star of the sea",s:2,t:["L","N"],u:3},
{n:"Sigrid",o:"Scandinavian",m:"Fair victory",s:2,t:["S","E"],u:3},
{n:"Siri",o:"Scandinavian",m:"Beautiful victory",s:2,t:["S","E"],u:3},
{n:"Solveig",o:"Scandinavian",m:"Sun strength",s:2,t:["L","S"],u:3},
{n:"Thea",o:"Scandinavian",m:"Divine gift, goddess",s:2,t:["G","F"],u:2},
{n:"Kirsten",o:"Scandinavian",m:"Christian",s:2,t:["F","E"],u:2},
{n:"Lena",o:"Scandinavian",m:"Light",s:2,t:["L","E"],u:2},
{n:"Randi",o:"Scandinavian",m:"Fair, bright shield",s:2,t:["L","S"],u:3},
{n:"Elif",o:"Turkish",m:"Slender, alif letter",s:2,t:["E","L"],u:2},
{n:"Esen",o:"Turkish",m:"Fresh breeze",s:2,t:["N","R"],u:3},
{n:"Esma",o:"Turkish",m:"Names, supreme",s:2,t:["S","W"],u:2},
{n:"Gul",o:"Turkish",m:"Rose flower",s:1,t:["N","V"],u:3},
{n:"Hilal",o:"Turkish",m:"Crescent moon",s:2,t:["L","N"],u:2},
{n:"Irem",o:"Turkish",m:"Garden of paradise",s:2,t:["G","N"],u:2},
{n:"Leyla",o:"Turkish",m:"Night, dark beauty",s:2,t:["N","E"],u:2},
{n:"Melike",o:"Turkish",m:"Queen",s:3,t:["S","E"],u:2},
{n:"Melis",o:"Turkish",m:"Honey bee",s:2,t:["N","V"],u:2},
{n:"Merve",o:"Turkish",m:"Sacred hill in Mecca",s:2,t:["F","N"],u:2},
{n:"Meryem",o:"Turkish",m:"Virgin Mary, beloved",s:3,t:["F","G"],u:2},
{n:"Naz",o:"Turkish",m:"Elegance, coquetry",s:1,t:["E","V"],u:2},
{n:"Nilüfer",o:"Turkish",m:"Water lily, lotus",s:3,t:["N","E"],u:2},
{n:"Seda",o:"Turkish",m:"Voice, echo",s:2,t:["R","V"],u:3},
{n:"Selin",o:"Turkish",m:"River, flowing",s:2,t:["N","R"],u:2},
{n:"Tugba",o:"Turkish",m:"A tree in paradise",s:2,t:["G","N"],u:2},
{n:"Yasemin",o:"Turkish",m:"Jasmine flower",s:3,t:["N","E"],u:2},
{n:"Yesim",o:"Turkish",m:"Jade stone",s:2,t:["N","E"],u:3},
{n:"Amara",o:"Mixed / Multicultural",m:"Eternal, blessed grace",s:3,t:["G","E"],u:2},
{n:"Ayla",o:"Mixed / Multicultural",m:"Moonlight, oak tree",s:2,t:["L","N"],u:2},
{n:"Kira",o:"Mixed / Multicultural",m:"Sun ray, beam of light",s:2,t:["L","E"],u:2},
{n:"Maia",o:"Mixed / Multicultural",m:"Great, nurturing mother",s:2,t:["G","F"],u:2},
{n:"Noa",o:"Mixed / Multicultural",m:"Motion, comfort",s:2,t:["F","V"],u:3},
{n:"Reva",o:"Mixed / Multicultural",m:"Rain, flowing river",s:2,t:["N","R"],u:3},
{n:"Sora",o:"Mixed / Multicultural",m:"Sky, infinite light",s:2,t:["L","R"],u:3},
{n:"Ziva",o:"Mixed / Multicultural",m:"Radiance, brilliant light",s:2,t:["L","E"],u:3},
{n:"Zola",o:"Mixed / Multicultural",m:"Tranquil, earth",s:2,t:["N","F"],u:3},
{n:"Aura",o:"Mixed / Multicultural",m:"Golden breeze, luminous",s:2,t:["L","N"],u:3},
{n:"Ember",o:"Mixed / Multicultural",m:"Glowing spark, warmth",s:2,t:["L","V"],u:3},
{n:"Lumi",o:"Mixed / Multicultural",m:"Snow, pure light",s:2,t:["L","N"],u:3},
{n:"Nova",o:"Mixed / Multicultural",m:"New star, brightness",s:2,t:["L","H"],u:3},
{n:"Nia",o:"Mixed / Multicultural",m:"Purpose, radiant, blessed",s:2,t:["F","L"],u:2},
{n:"Seren",o:"Mixed / Multicultural",m:"Star, serene",s:2,t:["L","F"],u:3},
{n:"Aylin",o:"Mixed / Multicultural",m:"Moon halo",s:2,t:["L","N"],u:3},
{n:"Zuri",o:"Mixed / Multicultural",m:"Breathtakingly beautiful",s:2,t:["E","N"],u:3},
{n:"Liana",o:"Mixed / Multicultural",m:"Light, graceful vine",s:3,t:["L","N"],u:3},
{n:"Thalia",o:"Mixed / Multicultural",m:"Blooming, flourishing",s:3,t:["N","H"],u:3},
];
export const BOYS=[
{n:"Abdullah",o:"Arabic",m:"Servant of God",s:3,t:["F","G"],u:1},
{n:"Ahmad",o:"Arabic",m:"Most praiseworthy",s:2,t:["F","S"],u:1},
{n:"Ahmed",o:"Arabic",m:"Praiseworthy, commendable",s:2,t:["F","S"],u:1},
{n:"Ali",o:"Arabic",m:"Elevated, noble",s:2,t:["S","E"],u:1},
{n:"Amin",o:"Arabic",m:"Trustworthy, faithful",s:2,t:["F","W"],u:2},
{n:"Amir",o:"Arabic",m:"Prince, commander",s:2,t:["S","E"],u:1},
{n:"Anas",o:"Arabic",m:"Friendly, sociable",s:2,t:["V","F"],u:2},
{n:"Anwar",o:"Arabic",m:"Brighter, more luminous",s:2,t:["L","S"],u:2},
{n:"Arif",o:"Arabic",m:"Knowledgeable, wise",s:2,t:["W","F"],u:2},
{n:"Ayman",o:"Arabic",m:"Blessed, right-hand",s:2,t:["G","F"],u:2},
{n:"Aziz",o:"Arabic",m:"Powerful, beloved",s:2,t:["S","V"],u:2},
{n:"Badr",o:"Arabic",m:"Full moon",s:1,t:["L","N"],u:2},
{n:"Bilal",o:"Arabic",m:"Moisture, first muezzin",s:2,t:["F","V"],u:1},
{n:"Dawud",o:"Arabic",m:"Beloved, of David",s:2,t:["V","F"],u:2},
{n:"Emad",o:"Arabic",m:"Pillar, support",s:2,t:["S","F"],u:2},
{n:"Faisal",o:"Arabic",m:"Decisive, sword",s:2,t:["S","W"],u:2},
{n:"Farhan",o:"Arabic",m:"Happy, joyful",s:2,t:["V","H"],u:2},
{n:"Faris",o:"Arabic",m:"Knight, horseman",s:2,t:["S","R"],u:2},
{n:"Fouad",o:"Arabic",m:"Heart",s:2,t:["V","F"],u:2},
{n:"Ghassan",o:"Arabic",m:"Youth, vigor",s:2,t:["H","S"],u:2},
{n:"Hamad",o:"Arabic",m:"Praised, commended",s:2,t:["F","S"],u:2},
{n:"Hamdan",o:"Arabic",m:"Praised, commended",s:2,t:["F","S"],u:2},
{n:"Hamid",o:"Arabic",m:"Praised, thankful",s:2,t:["F","G"],u:2},
{n:"Hamza",o:"Arabic",m:"Lion, strong",s:2,t:["S","N"],u:1},
{n:"Hani",o:"Arabic",m:"Happy, content",s:2,t:["V","H"],u:2},
{n:"Harith",o:"Arabic",m:"Plowman, cultivator",s:2,t:["N","S"],u:2},
{n:"Hasan",o:"Arabic",m:"Good, handsome",s:2,t:["E","V"],u:1},
{n:"Hussam",o:"Arabic",m:"Sharp sword",s:2,t:["S","W"],u:2},
{n:"Hussein",o:"Arabic",m:"Good, handsome",s:2,t:["E","V"],u:1},
{n:"Ibrahim",o:"Arabic",m:"Father of many, prophet",s:3,t:["F","G"],u:1},
{n:"Imad",o:"Arabic",m:"Pillar, backbone",s:2,t:["S","F"],u:2},
{n:"Jamal",o:"Arabic",m:"Beauty, grace",s:2,t:["E","V"],u:2},
{n:"Kamal",o:"Arabic",m:"Perfection, completion",s:2,t:["E","W"],u:2},
{n:"Kareem",o:"Arabic",m:"Noble, generous",s:2,t:["S","V"],u:2},
{n:"Khalid",o:"Arabic",m:"Eternal, immortal",s:2,t:["S","F"],u:1},
{n:"Khalil",o:"Arabic",m:"Friend, companion",s:2,t:["V","F"],u:2},
{n:"Mahmoud",o:"Arabic",m:"Praiseworthy",s:2,t:["F","S"],u:1},
{n:"Majed",o:"Arabic",m:"Glorious, noble",s:2,t:["S","E"],u:2},
{n:"Malek",o:"Arabic",m:"King, owner",s:2,t:["S","E"],u:2},
{n:"Marwan",o:"Arabic",m:"Flint stone, solid",s:2,t:["S","N"],u:2},
{n:"Mohammad",o:"Arabic",m:"Praiseworthy, prophet",s:3,t:["F","G"],u:1},
{n:"Musa",o:"Arabic",m:"Moses, drawn from water",s:2,t:["F","N"],u:1},
{n:"Mustafa",o:"Arabic",m:"Chosen one, prophet",s:3,t:["F","G"],u:1},
{n:"Nabil",o:"Arabic",m:"Noble, honorable",s:2,t:["S","E"],u:2},
{n:"Nasser",o:"Arabic",m:"Victory, helper",s:2,t:["S","H"],u:2},
{n:"Omar",o:"Arabic",m:"Flourishing, long-lived",s:2,t:["H","S"],u:1},
{n:"Qasim",o:"Arabic",m:"Divider, distributor",s:2,t:["W","F"],u:2},
{n:"Raed",o:"Arabic",m:"Pioneer, leader",s:1,t:["S","R"],u:2},
{n:"Rami",o:"Arabic",m:"Archer, loving",s:2,t:["S","V"],u:2},
{n:"Rayan",o:"Arabic",m:"Lush, gates of paradise",s:2,t:["G","N"],u:2},
{n:"Saad",o:"Arabic",m:"Happiness, good luck",s:1,t:["H","G"],u:2},
{n:"Saeed",o:"Arabic",m:"Happy, fortunate",s:2,t:["H","G"],u:2},
{n:"Saif",o:"Arabic",m:"Sword",s:1,t:["S","W"],u:2},
{n:"Salem",o:"Arabic",m:"Safe, peaceful",s:2,t:["F","V"],u:2},
{n:"Salim",o:"Arabic",m:"Peaceful, safe",s:2,t:["F","V"],u:2},
{n:"Salman",o:"Arabic",m:"Safe, peaceful",s:2,t:["F","V"],u:2},
{n:"Sami",o:"Arabic",m:"Elevated, sublime",s:2,t:["S","E"],u:2},
{n:"Samer",o:"Arabic",m:"Entertaining companion",s:2,t:["V","W"],u:2},
{n:"Sharif",o:"Arabic",m:"Noble, honorable",s:2,t:["S","E"],u:2},
{n:"Suleiman",o:"Arabic",m:"Peace, prophet Solomon",s:4,t:["F","W"],u:1},
{n:"Sultan",o:"Arabic",m:"King, ruler",s:2,t:["S","E"],u:2},
{n:"Tariq",o:"Arabic",m:"Morning star, one who knocks",s:2,t:["L","S"],u:2},
{n:"Umar",o:"Arabic",m:"Flourishing, long-lived",s:2,t:["H","S"],u:1},
{n:"Waleed",o:"Arabic",m:"Newborn child",s:2,t:["H","N"],u:2},
{n:"Wissam",o:"Arabic",m:"Medal, badge of honor",s:2,t:["S","E"],u:2},
{n:"Yahya",o:"Arabic",m:"God is merciful, John",s:3,t:["G","F"],u:2},
{n:"Youssef",o:"Arabic",m:"God increases, Joseph",s:2,t:["G","F"],u:1},
{n:"Yusuf",o:"Arabic",m:"God increases, prophet",s:2,t:["G","F"],u:1},
{n:"Zaid",o:"Arabic",m:"Growth, surplus",s:1,t:["H","S"],u:2},
{n:"Zein",o:"Arabic",m:"Beauty, grace",s:1,t:["E","L"],u:2},
{n:"Ziad",o:"Arabic",m:"Abundance, increase",s:2,t:["H","S"],u:2},
{n:"Adel",o:"Arabic",m:"Just, fair",s:2,t:["W","S"],u:2},
{n:"Akram",o:"Arabic",m:"Most generous",s:2,t:["V","S"],u:2},
{n:"Ameen",o:"Arabic",m:"Faithful, trustworthy",s:2,t:["F","W"],u:2},
{n:"Ayoub",o:"Arabic",m:"Prophet Job, patient",s:2,t:["F","S"],u:2},
{n:"Bassel",o:"Arabic",m:"Brave, lion",s:2,t:["S","N"],u:2},
{n:"Bassem",o:"Arabic",m:"Smiling",s:2,t:["V","H"],u:2},
{n:"Fadel",o:"Arabic",m:"Virtuous, excellent",s:2,t:["E","W"],u:2},
{n:"Fahd",o:"Arabic",m:"Leopard",s:1,t:["S","N"],u:2},
{n:"Faisal",o:"Arabic",m:"Decisive, sword",s:2,t:["S","W"],u:2},
{n:"Fawaz",o:"Arabic",m:"Successful",s:2,t:["H","S"],u:2},
{n:"Ghaith",o:"Arabic",m:"Rain, rainfall",s:1,t:["N","G"],u:3},
{n:"Ghazi",o:"Arabic",m:"Warrior, conqueror",s:2,t:["S","R"],u:2},
{n:"Hafiz",o:"Arabic",m:"Guardian, protector",s:2,t:["S","F"],u:2},
{n:"Haider",o:"Arabic",m:"Lion",s:2,t:["S","N"],u:2},
{n:"Hatem",o:"Arabic",m:"Generous, decisive",s:2,t:["V","S"],u:2},
{n:"Hazem",o:"Arabic",m:"Decisive, firm",s:2,t:["S","W"],u:2},
{n:"Hilal",o:"Arabic",m:"Crescent moon",s:2,t:["L","N"],u:2},
{n:"Hisham",o:"Arabic",m:"Generosity, breaks bread",s:2,t:["V","S"],u:2},
{n:"Idriss",o:"Arabic",m:"Studious, prophet Enoch",s:2,t:["W","F"],u:2},
{n:"Ihsan",o:"Arabic",m:"Goodness, perfection",s:2,t:["E","F"],u:2},
{n:"Imran",o:"Arabic",m:"Prosperity, abundance",s:2,t:["H","S"],u:2},
{n:"Ismail",o:"Arabic",m:"God will hear, prophet",s:3,t:["G","F"],u:1},
{n:"Jaber",o:"Arabic",m:"Comforter, one who heals",s:2,t:["V","F"],u:2},
{n:"Kassem",o:"Arabic",m:"Divider, distributor",s:2,t:["W","F"],u:2},
{n:"Karim",o:"Arabic",m:"Noble, generous",s:2,t:["S","V"],u:2},
{n:"Latif",o:"Arabic",m:"Gentle, kind",s:2,t:["V","E"],u:2},
{n:"Mahdi",o:"Arabic",m:"Guided by God, rightly guided",s:2,t:["G","F"],u:2},
{n:"Majd",o:"Arabic",m:"Glory, honor",s:1,t:["S","E"],u:2},
{n:"Mansour",o:"Arabic",m:"Victorious",s:2,t:["S","H"],u:2},
{n:"Mazen",o:"Arabic",m:"Cloud bearing rain",s:2,t:["N","H"],u:2},
{n:"Mohand",o:"Arabic",m:"Praiseworthy",s:2,t:["F","S"],u:2},
{n:"Mourad",o:"Arabic",m:"Desired, wished for",s:2,t:["H","V"],u:2},
{n:"Muath",o:"Arabic",m:"Refuge, shelter",s:1,t:["F","S"],u:3},
{n:"Musab",o:"Arabic",m:"Hardened, brave",s:2,t:["S","F"],u:3},
{n:"Nadeem",o:"Arabic",m:"Companion, friend",s:2,t:["V","W"],u:2},
{n:"Nawaf",o:"Arabic",m:"High, prominent",s:2,t:["S","L"],u:3},
{n:"Nizar",o:"Arabic",m:"Small amount, precious",s:2,t:["E","S"],u:3},
{n:"Nouh",o:"Arabic",m:"Prophet Noah, rest",s:1,t:["F","N"],u:2},
{n:"Nour",o:"Arabic",m:"Light",s:1,t:["L","F"],u:2},
{n:"Rafik",o:"Arabic",m:"Companion, friend",s:2,t:["V","W"],u:2},
{n:"Rashad",o:"Arabic",m:"Integrity, righteousness",s:2,t:["F","W"],u:2},
{n:"Rashid",o:"Arabic",m:"Rightly guided",s:2,t:["F","W"],u:2},
{n:"Rayyan",o:"Arabic",m:"Full of life, gates of heaven",s:2,t:["G","H"],u:2},
{n:"Saad",o:"Arabic",m:"Happiness, good luck",s:1,t:["H","G"],u:2},
{n:"Sabri",o:"Arabic",m:"Patient, enduring",s:2,t:["S","F"],u:2},
{n:"Sadiq",o:"Arabic",m:"Truthful, sincere",s:2,t:["F","W"],u:2},
{n:"Safwan",o:"Arabic",m:"Pure, rock",s:2,t:["F","N"],u:2},
{n:"Sameer",o:"Arabic",m:"Entertaining companion",s:2,t:["V","W"],u:2},
{n:"Samih",o:"Arabic",m:"Forgiving, tolerant",s:2,t:["V","F"],u:2},
{n:"Shakir",o:"Arabic",m:"Thankful, grateful",s:2,t:["F","G"],u:2},
{n:"Taha",o:"Arabic",m:"Letters of Quran, prophet",s:2,t:["F","G"],u:2},
{n:"Talal",o:"Arabic",m:"Rain, nice",s:2,t:["N","V"],u:2},
{n:"Tarek",o:"Arabic",m:"Morning star",s:2,t:["L","S"],u:2},
{n:"Walid",o:"Arabic",m:"Newborn",s:2,t:["H","N"],u:2},
{n:"Waseem",o:"Arabic",m:"Handsome, graceful",s:2,t:["E","V"],u:2},
{n:"Yazan",o:"Arabic",m:"Aspiration",s:2,t:["H","R"],u:3},
{n:"Younis",o:"Arabic",m:"Prophet Jonah, dove",s:2,t:["F","N"],u:2},
{n:"Zaher",o:"Arabic",m:"Bright, flourishing",s:2,t:["L","H"],u:2},
{n:"Zaki",o:"Arabic",m:"Pure, intelligent",s:2,t:["F","W"],u:2},
{n:"Zuhair",o:"Arabic",m:"Flowers, bright",s:2,t:["N","L"],u:2},
{n:"Aaron",o:"English",m:"Mountain of strength",s:2,t:["S","N"],u:2},
{n:"Adam",o:"English",m:"Earth, man",s:2,t:["N","F"],u:1},
{n:"Alexander",o:"English",m:"Defender of men",s:4,t:["S","F"],u:1},
{n:"Andrew",o:"English",m:"Strong, manly",s:2,t:["S","E"],u:2},
{n:"Anthony",o:"English",m:"Priceless, praiseworthy",s:3,t:["E","S"],u:2},
{n:"Arthur",o:"English",m:"Bear, noble",s:2,t:["S","N"],u:2},
{n:"Benjamin",o:"English",m:"Son of the right hand",s:4,t:["G","S"],u:1},
{n:"Cameron",o:"English",m:"Crooked river",s:3,t:["N","R"],u:2},
{n:"Charles",o:"English",m:"Free man",s:1,t:["R","S"],u:2},
{n:"Christopher",o:"English",m:"Bearer of Christ",s:3,t:["F","S"],u:1},
{n:"Daniel",o:"English",m:"God is my judge",s:3,t:["G","F"],u:1},
{n:"David",o:"English",m:"Beloved",s:2,t:["V","F"],u:1},
{n:"Dylan",o:"English",m:"Son of the sea",s:2,t:["N","R"],u:2},
{n:"Edward",o:"English",m:"Wealthy guardian",s:2,t:["S","E"],u:2},
{n:"Ethan",o:"English",m:"Strong, enduring",s:2,t:["S","F"],u:2},
{n:"Evan",o:"English",m:"Young warrior, God is gracious",s:2,t:["G","S"],u:2},
{n:"Felix",o:"English",m:"Happy, fortunate",s:2,t:["H","V"],u:2},
{n:"Finley",o:"English",m:"Fair warrior",s:2,t:["S","E"],u:2},
{n:"Frederick",o:"English",m:"Peaceful ruler",s:3,t:["F","S"],u:2},
{n:"Gabriel",o:"English",m:"God is my strength",s:3,t:["G","S"],u:2},
{n:"George",o:"English",m:"Farmer, earth worker",s:1,t:["N","S"],u:2},
{n:"Harry",o:"English",m:"Army ruler",s:2,t:["S","E"],u:2},
{n:"Henry",o:"English",m:"Home ruler",s:2,t:["S","E"],u:2},
{n:"Hugo",o:"English",m:"Mind, intellect",s:2,t:["W","E"],u:2},
{n:"Isaac",o:"English",m:"He laughs",s:2,t:["V","H"],u:2},
{n:"Jack",o:"English",m:"God is gracious",s:1,t:["G","S"],u:1},
{n:"Jacob",o:"English",m:"Supplanter, held by heel",s:2,t:["S","F"],u:1},
{n:"James",o:"English",m:"Supplanter",s:1,t:["S","E"],u:1},
{n:"Jasper",o:"English",m:"Treasurer, gemstone",s:2,t:["E","N"],u:3},
{n:"John",o:"English",m:"God is gracious",s:1,t:["G","F"],u:1},
{n:"Jonathan",o:"English",m:"God has given",s:3,t:["G","F"],u:2},
{n:"Joseph",o:"English",m:"God will increase",s:3,t:["G","H"],u:1},
{n:"Joshua",o:"English",m:"God is salvation",s:3,t:["G","F"],u:1},
{n:"Julian",o:"English",m:"Youthful, downy",s:3,t:["E","H"],u:2},
{n:"Liam",o:"English",m:"Strong-willed warrior",s:1,t:["S","R"],u:1},
{n:"Logan",o:"English",m:"Little hollow",s:2,t:["N","R"],u:2},
{n:"Lucas",o:"English",m:"Light",s:2,t:["L","E"],u:1},
{n:"Luke",o:"English",m:"Light, luminous",s:1,t:["L","E"],u:2},
{n:"Matthew",o:"English",m:"Gift of God",s:2,t:["G","F"],u:1},
{n:"Max",o:"English",m:"Greatest",s:1,t:["S","E"],u:2},
{n:"Michael",o:"English",m:"Who is like God",s:3,t:["G","F"],u:1},
{n:"Nathan",o:"English",m:"Gift from God",s:2,t:["G","F"],u:2},
{n:"Nicholas",o:"English",m:"Victory of the people",s:3,t:["S","H"],u:2},
{n:"Noah",o:"English",m:"Rest, comfort",s:2,t:["F","V"],u:1},
{n:"Oliver",o:"English",m:"Olive tree, peace",s:3,t:["N","F"],u:1},
{n:"Oscar",o:"English",m:"Spear of the Gods",s:2,t:["S","N"],u:2},
{n:"Owen",o:"English",m:"Young warrior, well born",s:2,t:["S","E"],u:2},
{n:"Patrick",o:"English",m:"Noble, patrician",s:2,t:["E","S"],u:2},
{n:"Peter",o:"English",m:"Rock, stone",s:2,t:["S","N"],u:2},
{n:"Richard",o:"English",m:"Brave ruler",s:2,t:["S","E"],u:2},
{n:"Robert",o:"English",m:"Bright fame",s:2,t:["L","S"],u:2},
{n:"Ryan",o:"English",m:"Little king",s:2,t:["S","E"],u:1},
{n:"Samuel",o:"English",m:"Heard by God",s:3,t:["G","F"],u:1},
{n:"Sebastian",o:"English",m:"Revered, venerable",s:4,t:["E","F"],u:2},
{n:"Simon",o:"English",m:"God has heard",s:2,t:["G","F"],u:2},
{n:"Thomas",o:"English",m:"Twin",s:2,t:["F","V"],u:1},
{n:"Victor",o:"English",m:"Conqueror, victory",s:2,t:["S","H"],u:2},
{n:"William",o:"English",m:"Resolute protector",s:3,t:["S","F"],u:1},
{n:"Zachary",o:"English",m:"God has remembered",s:3,t:["G","F"],u:2},
{n:"Axel",o:"English",m:"Father of peace",s:2,t:["F","S"],u:3},
{n:"Blake",o:"English",m:"Fair-haired, dark",s:1,t:["E","N"],u:2},
{n:"Chase",o:"English",m:"Hunter",s:1,t:["S","N"],u:2},
{n:"Cole",o:"English",m:"Charcoal, victory",s:1,t:["S","N"],u:2},
{n:"Connor",o:"English",m:"Lover of hounds",s:2,t:["V","N"],u:2},
{n:"Dominic",o:"English",m:"Lord, belonging to God",s:3,t:["G","F"],u:2},
{n:"Emmett",o:"English",m:"Universal, truth",s:2,t:["W","E"],u:3},
{n:"Finn",o:"English",m:"Fair, white",s:1,t:["E","N"],u:2},
{n:"Grant",o:"English",m:"Large, great",s:1,t:["S","E"],u:2},
{n:"Griffin",o:"English",m:"Strong lord",s:2,t:["S","E"],u:2},
{n:"Hunter",o:"English",m:"One who hunts",s:2,t:["S","N"],u:2},
{n:"Leo",o:"English",m:"Lion",s:2,t:["S","N"],u:2},
{n:"Lewis",o:"English",m:"Famous warrior",s:2,t:["S","E"],u:2},
{n:"Lincoln",o:"English",m:"Lake colony",s:2,t:["N","H"],u:2},
{n:"Mason",o:"English",m:"Stone worker",s:2,t:["N","S"],u:2},
{n:"Parker",o:"English",m:"Park keeper",s:2,t:["N","S"],u:2},
{n:"Spencer",o:"English",m:"Steward, administrator",s:2,t:["S","W"],u:2},
{n:"Wyatt",o:"English",m:"Brave in war",s:2,t:["S","R"],u:2},
{n:"Adrian",o:"Latin",m:"Dark, rich",s:3,t:["E","N"],u:2},
{n:"Ambrose",o:"Latin",m:"Immortal, divine",s:2,t:["F","E"],u:3},
{n:"Augustus",o:"Latin",m:"Great, magnificent",s:3,t:["S","E"],u:3},
{n:"Benedict",o:"Latin",m:"Blessed",s:3,t:["G","F"],u:3},
{n:"Bruno",o:"Latin",m:"Brown, bear",s:2,t:["N","S"],u:2},
{n:"Clement",o:"Latin",m:"Gentle, merciful",s:2,t:["V","F"],u:3},
{n:"Damian",o:"Latin",m:"To tame, subdue",s:3,t:["S","W"],u:2},
{n:"Dominic",o:"Latin",m:"Lord, belonging to God",s:3,t:["G","F"],u:2},
{n:"Emil",o:"Latin",m:"Rival, industrious",s:2,t:["S","E"],u:2},
{n:"Fabian",o:"Latin",m:"Bean grower",s:3,t:["N","S"],u:3},
{n:"Felix",o:"Latin",m:"Happy, fortunate",s:2,t:["H","V"],u:2},
{n:"Florian",o:"Latin",m:"Flower, blooming",s:3,t:["N","H"],u:3},
{n:"Julian",o:"Latin",m:"Youthful, downy",s:3,t:["E","H"],u:2},
{n:"Leo",o:"Latin",m:"Lion, brave",s:2,t:["S","N"],u:2},
{n:"Lucius",o:"Latin",m:"Light",s:3,t:["L","E"],u:3},
{n:"Magnus",o:"Latin",m:"Great",s:2,t:["S","E"],u:3},
{n:"Marcus",o:"Latin",m:"Of Mars, warlike",s:2,t:["S","E"],u:2},
{n:"Maximus",o:"Latin",m:"Greatest",s:3,t:["S","E"],u:3},
{n:"Milo",o:"Latin",m:"Soldier, gracious",s:2,t:["S","V"],u:3},
{n:"Pascal",o:"Latin",m:"Passover, Easter",s:2,t:["F","H"],u:3},
{n:"Paul",o:"Latin",m:"Small, humble",s:1,t:["F","E"],u:2},
{n:"Roman",o:"Latin",m:"Roman, strong",s:2,t:["S","H"],u:2},
{n:"Sebastian",o:"Latin",m:"Revered",s:4,t:["E","F"],u:2},
{n:"Titus",o:"Latin",m:"Title of honor",s:2,t:["S","E"],u:3},
{n:"Valentin",o:"Latin",m:"Strong, healthy",s:3,t:["S","V"],u:2},
{n:"Victor",o:"Latin",m:"Conqueror",s:2,t:["S","H"],u:2},
{n:"Alexander",o:"Greek",m:"Defender of the people",s:4,t:["S","F"],u:1},
{n:"Alexis",o:"Greek",m:"Helper, defender",s:3,t:["S","F"],u:2},
{n:"Basil",o:"Greek",m:"Royal, kingly",s:2,t:["S","E"],u:2},
{n:"Callum",o:"Greek",m:"Dove, peace",s:2,t:["F","V"],u:2},
{n:"Elias",o:"Greek",m:"My God is Yahweh",s:3,t:["G","F"],u:2},
{n:"Eugene",o:"Greek",m:"Well born, noble",s:3,t:["E","S"],u:2},
{n:"George",o:"Greek",m:"Farmer, earth worker",s:1,t:["N","S"],u:2},
{n:"Hector",o:"Greek",m:"Holding fast, restrain",s:2,t:["S","F"],u:2},
{n:"Jason",o:"Greek",m:"Healer",s:2,t:["F","S"],u:2},
{n:"Leon",o:"Greek",m:"Lion",s:2,t:["S","N"],u:2},
{n:"Leonidas",o:"Greek",m:"Son of a lion",s:4,t:["S","N"],u:3},
{n:"Nicholas",o:"Greek",m:"Victory of the people",s:3,t:["S","H"],u:1},
{n:"Orion",o:"Greek",m:"Rising star, hunter",s:3,t:["L","S"],u:3},
{n:"Philip",o:"Greek",m:"Lover of horses",s:2,t:["V","N"],u:2},
{n:"Phoenix",o:"Greek",m:"Dark red, reborn from ashes",s:2,t:["H","S"],u:3},
{n:"Theodore",o:"Greek",m:"Gift of God",s:3,t:["G","F"],u:2},
{n:"Thomas",o:"Greek",m:"Twin",s:2,t:["F","V"],u:1},
{n:"Xander",o:"Greek",m:"Defender of men",s:2,t:["S","F"],u:2},
{n:"Yannis",o:"Greek",m:"God is gracious",s:2,t:["G","F"],u:3},
{n:"Zephyr",o:"Greek",m:"West wind",s:2,t:["N","R"],u:3},
{n:"Evander",o:"Greek",m:"Good man",s:3,t:["E","S"],u:3},
{n:"Arash",o:"Persian",m:"Brightness, hero archer",s:2,t:["L","S"],u:3},
{n:"Arman",o:"Persian",m:"Wish, ideal",s:2,t:["H","R"],u:2},
{n:"Armin",o:"Persian",m:"Defender",s:2,t:["S","F"],u:2},
{n:"Cyrus",o:"Persian",m:"Sun, throne",s:2,t:["L","S"],u:2},
{n:"Darius",o:"Persian",m:"Upholder of good",s:3,t:["S","F"],u:2},
{n:"Farhad",o:"Persian",m:"Happiness, abundance",s:2,t:["H","V"],u:3},
{n:"Jamshid",o:"Persian",m:"Shining throne",s:2,t:["L","S"],u:3},
{n:"Kamran",o:"Persian",m:"Successful",s:2,t:["H","S"],u:2},
{n:"Kaveh",o:"Persian",m:"Majestic, blacksmith hero",s:2,t:["S","N"],u:3},
{n:"Kian",o:"Persian",m:"Grace, ancient",s:2,t:["E","H"],u:2},
{n:"Mehran",o:"Persian",m:"Great, sun",s:2,t:["L","S"],u:3},
{n:"Nima",o:"Persian",m:"Blessing",s:2,t:["G","F"],u:2},
{n:"Omid",o:"Persian",m:"Hope",s:2,t:["H","F"],u:2},
{n:"Ramin",o:"Persian",m:"Joy, happiness",s:2,t:["V","H"],u:2},
{n:"Reza",o:"Persian",m:"Contentment, satisfaction",s:2,t:["F","H"],u:2},
{n:"Roshan",o:"Persian",m:"Shining, bright",s:2,t:["L","H"],u:2},
{n:"Siavash",o:"Persian",m:"Owner of black horse",s:3,t:["S","N"],u:3},
{n:"Sina",o:"Persian",m:"Straight, upright",s:2,t:["S","E"],u:2},
{n:"Soroush",o:"Persian",m:"Messenger, joy",s:2,t:["G","V"],u:3},
{n:"Vahid",o:"Persian",m:"Unique, singular",s:2,t:["E","S"],u:3},
{n:"Adrien",o:"French",m:"From the Adriatic",s:3,t:["N","E"],u:2},
{n:"Alexandre",o:"French",m:"Defender of men",s:3,t:["S","F"],u:2},
{n:"Antoine",o:"French",m:"Priceless, praiseworthy",s:3,t:["E","S"],u:2},
{n:"Armand",o:"French",m:"Army man",s:2,t:["S","R"],u:3},
{n:"Clement",o:"French",m:"Gentle, merciful",s:2,t:["V","F"],u:2},
{n:"Edouard",o:"French",m:"Wealthy guardian",s:3,t:["S","E"],u:3},
{n:"Emile",o:"French",m:"Rival, industrious",s:2,t:["S","E"],u:2},
{n:"Francois",o:"French",m:"Free man",s:2,t:["R","E"],u:2},
{n:"Gabriel",o:"French",m:"God is my strength",s:3,t:["G","S"],u:2},
{n:"Henri",o:"French",m:"Home ruler",s:2,t:["S","E"],u:2},
{n:"Hugo",o:"French",m:"Mind, intellect",s:2,t:["W","E"],u:2},
{n:"Julien",o:"French",m:"Youthful",s:3,t:["E","H"],u:2},
{n:"Laurent",o:"French",m:"Laurel, victory",s:2,t:["S","N"],u:2},
{n:"Leo",o:"French",m:"Lion",s:2,t:["S","N"],u:2},
{n:"Louis",o:"French",m:"Famous warrior",s:2,t:["S","E"],u:2},
{n:"Lucas",o:"French",m:"Light",s:2,t:["L","E"],u:1},
{n:"Mathieu",o:"French",m:"Gift of God",s:3,t:["G","F"],u:2},
{n:"Maxime",o:"French",m:"Greatest",s:2,t:["S","E"],u:2},
{n:"Nicolas",o:"French",m:"Victory of the people",s:3,t:["S","H"],u:2},
{n:"Noel",o:"French",m:"Christmas, born at Christmas",s:2,t:["H","F"],u:2},
{n:"Olivier",o:"French",m:"Olive tree, peace",s:3,t:["N","F"],u:2},
{n:"Pierre",o:"French",m:"Rock, stone",s:1,t:["S","N"],u:2},
{n:"Raphael",o:"French",m:"God has healed",s:3,t:["G","F"],u:2},
{n:"Theo",o:"French",m:"Divine gift",s:2,t:["G","F"],u:2},
{n:"Tristan",o:"French",m:"Noise, tumult",s:2,t:["S","R"],u:2},
{n:"Valentin",o:"French",m:"Strong, brave",s:3,t:["S","V"],u:2},
{n:"Xavier",o:"French",m:"New house, bright",s:2,t:["L","H"],u:2},
{n:"Alessandro",o:"Italian",m:"Defender of men",s:4,t:["S","F"],u:2},
{n:"Andrea",o:"Italian",m:"Strong, manly",s:3,t:["S","E"],u:2},
{n:"Angelo",o:"Italian",m:"Angel, messenger",s:3,t:["F","E"],u:2},
{n:"Antonio",o:"Italian",m:"Priceless",s:4,t:["E","S"],u:2},
{n:"Bruno",o:"Italian",m:"Brown, bear",s:2,t:["N","S"],u:2},
{n:"Carlo",o:"Italian",m:"Free man",s:2,t:["R","E"],u:2},
{n:"Davide",o:"Italian",m:"Beloved",s:3,t:["V","F"],u:2},
{n:"Elia",o:"Italian",m:"My God is Yahweh",s:3,t:["G","F"],u:2},
{n:"Enzo",o:"Italian",m:"Home ruler, giant",s:2,t:["S","E"],u:3},
{n:"Federico",o:"Italian",m:"Peaceful ruler",s:4,t:["F","S"],u:2},
{n:"Filippo",o:"Italian",m:"Lover of horses",s:3,t:["V","N"],u:2},
{n:"Francesco",o:"Italian",m:"Free man",s:3,t:["R","E"],u:2},
{n:"Gabriele",o:"Italian",m:"God is my strength",s:4,t:["G","S"],u:2},
{n:"Giorgio",o:"Italian",m:"Farmer, earth worker",s:3,t:["N","S"],u:2},
{n:"Giovanni",o:"Italian",m:"God is gracious",s:4,t:["G","F"],u:2},
{n:"Luca",o:"Italian",m:"Light",s:2,t:["L","E"],u:2},
{n:"Marco",o:"Italian",m:"Of Mars, warlike",s:2,t:["S","E"],u:1},
{n:"Matteo",o:"Italian",m:"Gift of God",s:3,t:["G","F"],u:2},
{n:"Paolo",o:"Italian",m:"Small, humble",s:3,t:["F","E"],u:2},
{n:"Raffaele",o:"Italian",m:"God has healed",s:4,t:["G","F"],u:2},
{n:"Riccardo",o:"Italian",m:"Brave ruler",s:3,t:["S","E"],u:2},
{n:"Roberto",o:"Italian",m:"Bright fame",s:3,t:["L","S"],u:2},
{n:"Romeo",o:"Italian",m:"Pilgrim to Rome",s:3,t:["F","V"],u:3},
{n:"Salvatore",o:"Italian",m:"Savior",s:4,t:["G","F"],u:2},
{n:"Stefano",o:"Italian",m:"Crown",s:3,t:["S","E"],u:2},
{n:"Valentino",o:"Italian",m:"Strong, brave",s:4,t:["S","V"],u:2},
{n:"Aidan",o:"Celtic / Irish",m:"Little fire",s:2,t:["L","S"],u:2},
{n:"Angus",o:"Celtic / Irish",m:"One strength",s:2,t:["S","E"],u:3},
{n:"Brendan",o:"Celtic / Irish",m:"Prince, sword",s:2,t:["S","E"],u:2},
{n:"Ciaran",o:"Celtic / Irish",m:"Dark, black",s:2,t:["N","E"],u:3},
{n:"Cillian",o:"Celtic / Irish",m:"War, strife",s:2,t:["S","R"],u:3},
{n:"Conor",o:"Celtic / Irish",m:"Lover of hounds",s:2,t:["V","N"],u:2},
{n:"Declan",o:"Celtic / Irish",m:"Full of goodness",s:2,t:["E","F"],u:2},
{n:"Eoghan",o:"Celtic / Irish",m:"Born of the yew tree",s:2,t:["N","S"],u:3},
{n:"Fionn",o:"Celtic / Irish",m:"Fair, white",s:1,t:["E","N"],u:3},
{n:"Killian",o:"Celtic / Irish",m:"Bright-headed, small church",s:3,t:["L","F"],u:2},
{n:"Liam",o:"Celtic / Irish",m:"Strong-willed warrior",s:1,t:["S","R"],u:1},
{n:"Lorcan",o:"Celtic / Irish",m:"Little fierce one",s:2,t:["S","R"],u:3},
{n:"Niall",o:"Celtic / Irish",m:"Champion",s:1,t:["S","E"],u:3},
{n:"Ronan",o:"Celtic / Irish",m:"Little seal",s:2,t:["N","V"],u:3},
{n:"Sean",o:"Celtic / Irish",m:"God is gracious",s:1,t:["G","F"],u:2},
{n:"Tiernan",o:"Celtic / Irish",m:"Little lord",s:2,t:["S","E"],u:3},
{n:"Tomas",o:"Celtic / Irish",m:"Twin",s:2,t:["F","V"],u:2},
{n:"Anders",o:"Scandinavian",m:"Strong, manly",s:2,t:["S","E"],u:3},
{n:"Bjorn",o:"Scandinavian",m:"Bear",s:1,t:["S","N"],u:3},
{n:"Erik",o:"Scandinavian",m:"Ever ruler",s:2,t:["S","E"],u:2},
{n:"Finn",o:"Scandinavian",m:"Fair, white",s:1,t:["E","N"],u:2},
{n:"Gunnar",o:"Scandinavian",m:"Bold warrior",s:2,t:["S","R"],u:3},
{n:"Gustav",o:"Scandinavian",m:"Staff of the gods",s:2,t:["S","G"],u:3},
{n:"Ivar",o:"Scandinavian",m:"Archer, yew warrior",s:2,t:["S","N"],u:3},
{n:"Johan",o:"Scandinavian",m:"God is gracious",s:2,t:["G","F"],u:2},
{n:"Jonas",o:"Scandinavian",m:"Dove, peace",s:2,t:["F","V"],u:2},
{n:"Lars",o:"Scandinavian",m:"Laurel, victory",s:1,t:["S","N"],u:3},
{n:"Leif",o:"Scandinavian",m:"Heir, descendant",s:1,t:["H","S"],u:3},
{n:"Magnus",o:"Scandinavian",m:"Great",s:2,t:["S","E"],u:3},
{n:"Nils",o:"Scandinavian",m:"Victory of the people",s:1,t:["S","H"],u:3},
{n:"Olaf",o:"Scandinavian",m:"Ancestor's relic",s:2,t:["H","S"],u:3},
{n:"Oskar",o:"Scandinavian",m:"Spear of the Gods",s:2,t:["S","N"],u:2},
{n:"Sven",o:"Scandinavian",m:"Young man, youth",s:1,t:["H","S"],u:3},
{n:"Thor",o:"Scandinavian",m:"Thunder god",s:1,t:["S","N"],u:3},
{n:"Ulf",o:"Scandinavian",m:"Wolf",s:1,t:["S","N"],u:4},
{n:"Ahmet",o:"Turkish",m:"Praiseworthy",s:2,t:["F","S"],u:2},
{n:"Berk",o:"Turkish",m:"Strong, solid",s:1,t:["S","N"],u:3},
{n:"Burak",o:"Turkish",m:"Lightning",s:2,t:["L","S"],u:2},
{n:"Deniz",o:"Turkish",m:"Sea, ocean",s:2,t:["N","R"],u:2},
{n:"Emre",o:"Turkish",m:"Friend, brother",s:2,t:["V","F"],u:2},
{n:"Enes",o:"Turkish",m:"Friendly, sociable",s:2,t:["V","F"],u:2},
{n:"Erdem",o:"Turkish",m:"Virtue, wisdom",s:2,t:["W","E"],u:3},
{n:"Fatih",o:"Turkish",m:"Conqueror",s:2,t:["S","H"],u:2},
{n:"Kaan",o:"Turkish",m:"King of kings",s:1,t:["S","E"],u:2},
{n:"Kemal",o:"Turkish",m:"Maturity, perfection",s:2,t:["E","W"],u:2},
{n:"Mert",o:"Turkish",m:"Manly, brave",s:1,t:["S","E"],u:2},
{n:"Onur",o:"Turkish",m:"Honor, dignity",s:2,t:["S","E"],u:2},
{n:"Omer",o:"Turkish",m:"Life, flourishing",s:2,t:["H","S"],u:2},
{n:"Serdar",o:"Turkish",m:"Commander, leader",s:2,t:["S","E"],u:2},
{n:"Talha",o:"Turkish",m:"Kind of tree",s:2,t:["N","F"],u:2},
{n:"Tolga",o:"Turkish",m:"Helmet",s:2,t:["S","N"],u:3},
{n:"Ufuk",o:"Turkish",m:"Horizon",s:2,t:["H","R"],u:3},
{n:"Umut",o:"Turkish",m:"Hope",s:2,t:["H","F"],u:2},
{n:"Yavuz",o:"Turkish",m:"Stern, resolute",s:2,t:["S","E"],u:3},
{n:"Yunus",o:"Turkish",m:"Jonah, dove",s:2,t:["F","N"],u:2},
{n:"Zafer",o:"Turkish",m:"Victory, triumph",s:2,t:["S","H"],u:2},
{n:"Zain",o:"Mixed / Multicultural",m:"Beauty, grace",s:1,t:["E","L"],u:2},
{n:"Idris",o:"Mixed / Multicultural",m:"Studious, eager lord",s:2,t:["W","F"],u:2},
{n:"Laith",o:"Mixed / Multicultural",m:"Lion",s:1,t:["S","N"],u:2},
{n:"Nael",o:"Mixed / Multicultural",m:"Achiever, winner",s:1,t:["H","S"],u:3},
{n:"Soren",o:"Mixed / Multicultural",m:"Stern, serious",s:2,t:["W","S"],u:3},
{n:"Faris",o:"Mixed / Multicultural",m:"Knight, horseman",s:2,t:["S","R"],u:2},
{n:"Jad",o:"Mixed / Multicultural",m:"Gift, generous",s:1,t:["G","V"],u:2},
{n:"Zane",o:"Mixed / Multicultural",m:"God is gracious",s:1,t:["G","E"],u:2},
{n:"Ayan",o:"Mixed / Multicultural",m:"Gift of God",s:2,t:["G","F"],u:3},
{n:"Elian",o:"Mixed / Multicultural",m:"My God is Yahweh",s:3,t:["G","F"],u:3},
{n:"Rayan",o:"Mixed / Multicultural",m:"Gates of paradise",s:2,t:["G","N"],u:2},
{n:"Roshan",o:"Mixed / Multicultural",m:"Bright, shining",s:2,t:["L","H"],u:2},
{n:"Cyrus",o:"Mixed / Multicultural",m:"Sun, throne",s:2,t:["L","S"],u:2},
{n:"Kian",o:"Mixed / Multicultural",m:"Grace, ancient",s:2,t:["E","H"],u:2},
{n:"Orion",o:"Mixed / Multicultural",m:"Rising star, hunter",s:3,t:["L","S"],u:3},
{n:"Phoenix",o:"Mixed / Multicultural",m:"Reborn, dark red",s:2,t:["H","S"],u:3},
{n:"Zephyr",o:"Mixed / Multicultural",m:"West wind",s:2,t:["N","R"],u:3},
{n:"Jasper",o:"Mixed / Multicultural",m:"Treasurer",s:2,t:["E","N"],u:3},
{n:"Caspian",o:"Mixed / Multicultural",m:"Of the Caspian sea",s:3,t:["N","R"],u:4},
{n:"Evander",o:"Mixed / Multicultural",m:"Good man",s:3,t:["E","S"],u:4},
{n:"Lysander",o:"Mixed / Multicultural",m:"Liberator",s:3,t:["R","S"],u:4},
];
